# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php 
php:
  - 5.4

env:
  - DB=MYSQL CORE_RELEASE=3.1
  - DB=MYSQL CORE_RELEASE=3

before_script:
  - mkdir $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - ./.travis/install_tika.sh
  - sudo ./.travis/install_pdftotext.sh
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit --verbose textextraction/tests/
